name: "Sandbox Site CI"

on:
  workflow_call:
    secrets:
      terminus_token:
        required: true
      sandbox_site_name:
        required: true

jobs:
  composer_update:
    name: "run composer update"
    runs-on: ubuntu-latest
    steps:
      - name: wait until all prs accross all dev repos are merged
        run: sleep 5
      - name: checkout-repo
        uses: actions/checkout/@v2
      - name: include php and composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: composer update
        run: |
          php --version
          composer --version
      - name: Install Terminus
        run: |
          mkdir -p ~/terminus && cd ~/terminus
          curl -L https://github.com/pantheon-systems/terminus/releases/download/3.6.0/terminus.phar --output terminus
          chmod +x terminus
          ./terminus self:update
          sudo ln -s ~/terminus/terminus /usr/local/bin/terminus
      - name: login to terminus
        run: terminus auth:login --machine-token=${{ secrets.terminus_token }}
      - name: check terminus
        run: |
          echo terminus --version
          echo terminus auth:whoami
      - name: run bash update script
        run: ./update-sctipt.bash
        env:
          SANDBOX_SITE_NAME: ${{ secrets.sandbox_site_name }}