name: "Sandbox Site CI"

on:
  workflow_call:
    secrets:
      terminus_token:
        required: true
      sandbox_site_name:
        required: true
      ssh_key:
        required: true

jobs:
  composer_update:
    name: Update and Deploy Developer Sandbox
    runs-on: ubuntu-latest
    steps:
      - name: wait until all prs accross all dev repos are merged
        run: sleep 5
      - name: checkout-repo
        uses: actions/checkout/@v2
      - name: setup ssh
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ssh_key }}
      - name: include php and composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: composer update
        run: |
          composer update-upstream-dependencies
          composer update
      - name: push changes back to repos
        run: |
          git add .
          git commit -m --verbose date +"%d-%m-%Y-%T"
      - name: Install Terminus
        run: |
          mkdir -p ~/terminus && cd ~/terminus
          curl -L https://github.com/pantheon-systems/terminus/releases/download/3.6.0/terminus.phar --output terminus
          chmod +x terminus
          ./terminus self:update
          sudo ln -s ~/terminus/terminus /usr/local/bin/terminus
      - name: login to terminus
        run: terminus auth:login --machine-token=${{ secrets.terminus_token }}
      - name: run bash update script
        run: |
          terminus site:upstream:clear-cache ${{ secrets.sandbox_site_name }}
          terminus upstream:updates:apply ${{ secrets.sandbox_site_name }}.dev --accept-upstream
          terminus env:deploy ${{ secrets.sandbox_site_name }}.test --yes
          terminus env:deploy ${{ secrets.sandbox_site_name }}.live --yes --updatedb --cc
          terminus remote:drush ${{ secrets.sandbox_site_name }}.live -- cr
          terminus remote:drush ${{ secrets.sandbox_site_name }}.live -- en media_alias_display media_entity_file_replace media_file_delete menu_block ckeditor5_paste_filter scheduler layout_builder_iframe_modal linkit administerusersbyrole google_tag menu_firstchild responsive_preview anchor_link smtp recaptcha_v3 rebuild_cache_access ckeditor5_bootstrap_accordion ucb_drush_commands menu_item_extras ucb_styled_block ucb_linkmod --yes
          terminus remote:drush ${{ secrets.sandbox_site_name }}.live -- features:import cu_boulder_content_types --yes
          terminus remote:drush ${{ secrets.sandbox_site_name }}.live -- config:import --partial --source=/code/web/profiles/custom/boulder_profile/config/install --yes
          terminus remote:drush ${{ secrets.sandbox_site_name }}.live -- updb --yes;
          terminus remote:drush ${{ secrets.sandbox_site_name }}.live -- cr;
